version: '3.8'
volumes:
    postgres_data:
    redis_data:
    mongo_data:
services:
    abacuza-postgres:
        image: daxnet/abacuza-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=abacuza
        volumes:
            - postgres_data:/data:Z
        ports:
            - "5432:5432"
    abacuza-redis:
        image: daxnet/abacuza-redis
        volumes:
            - redis_data:/data:Z
        ports:
            - "6379:6379"
    abacuza-mongo:
        image: daxnet/abacuza-mongo
        volumes:
            - mongo_data:/data/db:Z
        ports:
            - "27017:27017"
    abacuza-cluster-service:
        image: daxnet/abacuza-cluster-service
        ports:
            - "9023:9023"
        depends_on: 
            - abacuza-mongo
            - abacuza-redis
        links: 
            - abacuza-mongo
            - abacuza-redis
        environment: 
            - mongo__connectionString=mongodb://abacuza-mongo:27017
            - mongo__database=abacuza-clusters
            - redis__connectionString=abacuza-redis:6379
    abacuza-job-scheduler-service:
        image: daxnet/abacuza-job-scheduler-service
        ports:
            - "9024:9024"
        depends_on: 
            - abacuza-mongo
            - abacuza-postgres
            - abacuza-redis
        links:
            - abacuza-mongo
            - abacuza-postgres
            - abacuza-redis
        environment: 
            - mongo__connectionString=mongodb://abacuza-mongo:27017
            - mongo__database=abacuza-job-schedulers
            - redis__connectionString=abacuza-redis:6379
            - quartz__driverDelegateType=Quartz.Impl.AdoJobStore.PostgreSQLDelegate, Quartz
            - quartz__dataSource__provider=Npgsql
            - quartz__dataSource__connectionString=User ID=postgres;Password=postgres;Host=abacuza-postgres;Port=5432;Database=abacuza
            - services__clusterService__url=http://abacuza-cluster-service:9023
            - services__clusterService__timeout=3m
            - services__clusterService__retries=5

