version: '3.8'
volumes:
    postgres_data:
    redis_data:
    mongo_data:
    s3_data:
services:
    abacuza-postgres:
        image: daxnet/abacuza-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=abacuza
        volumes:
            - postgres_data:/data:Z
        ports:
            - "5432:5432"
    abacuza-redis:
        image: daxnet/abacuza-redis
        volumes:
            - redis_data:/data:Z
        ports:
            - "6379:6379"
    abacuza-mongo:
        image: daxnet/abacuza-mongo
        volumes:
            - mongo_data:/data/db:Z
        ports:
            - "27017:27017"
    abacuza-cluster-service:
        image: daxnet/abacuza-cluster-service
        ports:
            - "9023:9023"
        depends_on: 
            - abacuza-mongo
            - abacuza-redis
        links: 
            - abacuza-mongo
            - abacuza-redis
        environment: 
            - mongo__connectionString=mongodb://abacuza-mongo:27017
            - mongo__database=abacuza-clusters
            - redis__connectionString=abacuza-redis:6379
    abacuza-job-scheduler-service:
        image: daxnet/abacuza-job-scheduler-service
        ports:
            - "9024:9024"
        depends_on: 
            - abacuza-mongo
            - abacuza-postgres
            - abacuza-redis
        links:
            - abacuza-mongo
            - abacuza-postgres
            - abacuza-redis
        environment: 
            - mongo__connectionString=mongodb://abacuza-mongo:27017
            - mongo__database=abacuza-job-schedulers
            - redis__connectionString=abacuza-redis:6379
            - quartz__driverDelegateType=Quartz.Impl.AdoJobStore.PostgreSQLDelegate, Quartz
            - quartz__dataSource__provider=Npgsql
            - quartz__dataSource__connectionString=User ID=postgres;Password=postgres;Host=abacuza-postgres;Port=5432;Database=abacuza
            - services__clusterService__url=http://abacuza-cluster-service:9023
            - services__clusterService__timeout=3m
            - services__clusterService__retries=5
    abacuza-minio:
        image: minio/minio
        volumes:
            - s3_data:/data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: server /data
        restart: always
    abacuza-createbucket:
        image: minio/mc
        depends_on:
            - abacuza-minio
        entrypoint: |
            /bin/sh -c ' 
            for i in $$( seq 1 5 );do
            /usr/bin/mc config host add abacuza http://abacuza-minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
            test=$$(/usr/bin/mc ls | grep data);
            if [[ -z $$test ]]; then
                /usr/bin/mc mb abacuza/data;
                echo "Waiting for bucket to be created";
                sleep 5;
            else 
                break;
            fi; 
            done;
            if [[ -z $$test ]]; then exit -1; else exit 0; fi 
            '
    abacuza-livy-spark:
        image: daxnet/abacuza-livy-spark
        depends_on: 
            - abacuza-minio
        links: 
            - abacuza-minio
        ports:
            - 8998:8998
            - 4040:4040
        environment: 
            - ABACUZA_SPARK_MASTER=local[*]
            - ABACUZA_AWS_ENDPOINT=http://abacuza-minio:9000
            - ABACUZA_AWS_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - ABACUZA_AWS_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY